package diffence

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"strings"
)

const (
	diffSep = "diff --git a"
	pathSep = " b/"
)

// DiffItem is a diff struct for an inidividual file
type DiffItem struct {
	raw      string
	filePath string
	// addedText string
	// match        bool
	// matchedRules []rule
}

// SplitDiffs splits a single diff txt into an individual DiffItem for each file changed
func SplitDiffs(r io.Reader) ([]DiffItem, error) {

	var err error
	scanner := bufio.NewScanner(r)
	scanner.Split(ScanDiffs)

	// copy to temporary buffer because gets overwritten otherwise
	// https://golang.org/pkg/bufio/#Scanner.Bytes
	// "Bytes returns the most recent token generated by a call to Scan. The underlying array may point to data that will be OVERWRITTEN by a subsequent call to Scan. It does no allocation."
	buffer := bytes.NewBuffer(make([]byte, 0))
	items := []DiffItem{}
	BOF := true

	for scanner.Scan() {
		buffer.Write(scanner.Bytes())
		raw := buffer.String()
		// strip cruft from BOF (Beginning Of File) if necessary
		if BOF == true && !strings.HasPrefix(raw, diffSep) {
			BOF = false
			buffer.Reset()
			continue
		}
		filePath, err := extractFilePath(raw)
		if err != nil {
			return items, err
		}
		items = append(items, DiffItem{
			raw:      raw,
			filePath: filePath,
		})
		buffer.Reset()
	}

	if len(items) < 1 {
		return items, errors.New("Not valid diff content")
	}

	if err != nil {
		return items, err
	}

	return items, scanner.Err()
}

func extractHeader(in string) (string, error) {
	newLineIndex := strings.Index(in, "\n")
	if newLineIndex < 0 {
		return "", fmt.Errorf("not valid diff content:\n\n%s", in)
	}
	return in[:newLineIndex], nil
}

func extractFilePath(in string) (string, error) {
	pathBIndex := strings.Index(in, pathSep)
	newLineIndex := strings.Index(in, "\n")
	if pathBIndex >= 0 && newLineIndex > pathBIndex {
		return in[pathBIndex+len(pathSep) : newLineIndex], nil
	}
	return "", fmt.Errorf("Not valid diff content:\n%s", in)
}

// ScanDiffs splits on the diff of an inidividual file
func ScanDiffs(data []byte, atEOF bool) (advance int, token []byte, err error) {
	if atEOF && len(data) == 0 {
		return 0, nil, nil
	}

	k, byteIndex, diffSepEndIndex := 0, 0, 0
	dataLen := len(data) - 1
	diffSepLen := len(diffSep)

	// loop until no more bytes left to read in this chunk of data
	for k < dataLen {
		// find the next newline
		if i := bytes.IndexByte(data[k:], '\n'); i >= 0 {
			// how far advanced already (k)
			// index after last \n char (+ i)
			// start at next byte (+ 1)
			byteIndex = k + i + 1
			diffSepEndIndex = byteIndex + diffSepLen
			if diffSepEndIndex < dataLen && string(data[byteIndex:diffSepEndIndex]) == diffSep {
				return byteIndex, dropCR(data[0 : k+i]), nil
			}
			k += i + 1
		} else {
			k = dataLen
		}
	}
	// If we're at EOF, we have a final, non-terminated line. Return it.
	if atEOF {
		return len(data), dropCR(data), nil
	}
	// Request more data.
	return 0, nil, nil
}

// dropCR drops a terminal \r from the data.
func dropCR(data []byte) []byte {
	if len(data) > 0 && data[len(data)-1] == '\r' {
		return data[0 : len(data)-1]
	}
	return data
}
